[workspace]
resolver = "2"
members = ["vault", "factory", "types", "faucet"]

[workspace.dependencies]
soroban-sdk = "=26.1.1"
stellar-contract-utils = { git = "https://github.com/OpenZeppelin/stellar-contracts", rev = "a9c42169000638da937577f592ebf61a7a3c94ca" }

[profile.release]
opt-level = "z"
overflow-checks = true
strip = "symbols"
panic = "abort"
codegen-units = 1
lto = true
